os: linux

language: node_js
node_js:
  - "8"
  - "10"
  - "12"

env:
  global:
    - DISPLAY=:99.0

matrix:
  fast_finish: true
  include:
    - os: linux
      node_js: "10"
      env: CXX=g++-4.8 
      
    - os: linux
      node_js: "10"
      env: CXX=g++-4.8 TEST_SUITE=lint
      
    - os: linux
      compiler: linux-gcc7-release
      addons: *gcc7
      env: CC='gcc-7' CXX='g++-7' BUILD_TYPE='Release' TEST_SUITE=coveralls
      dist: bionic
      script: npm run $TEST_SUITE

    - os: osx
      osx_image: xcode11
      node_js: "10"
      compiler: xcode11-clang-release
      env: CXX='clang++' BUILD_TYPE='Release' TEST_SUITE=coveralls

    - os: osx
      osx_image: xcode11
      node_js: "12"
      compiler: xcode11-clang-release
      env: CXX='clang++' BUILD_TYPE='Release' TEST_SUITE=coveralls
